### ISSUE TITLE
Right way to import tessdata 

### ISSUE THREAD

**Issue by alfred42** [FeiZhuNiU/OCRDemo#1]
Steps
1. Make a folder named "tessdata" in %TESSBASE_PATH%
2. Put the data file into the tessdata folder.

For example,
If your TESSBASE_PATH is "/mnt/sdcard/tesseract", you need make a dir named "tessdata", then put the data file under "/mnt/sdcard/tesseract/tessdata/"

**Comment by FeiZhuNiU** [comment]
fixed 
no more need to worry about it
