### ISSUE TITLE
Solution for OCR

### ISSUE THREAD

**Issue by alfred42** [FeiZhuNiU/OCRDemo#2]
1. No error on my Nexus 5.
2. Can return the correct English or digit. But Chinese is not correct in most time.
3. I think you should check the size of the picture, if it is too big, we should zoom it before scanning. It will make the process much faster.
4. Wrap the OCR lib for our use.
5. We need to discuss the UI design for the front-end.

**Comment by FeiZhuNiU** [comment]
size adjust and binaryzation have been added
libs/language packaged with apk
ui design moved to another issue
